name: Generate SEC RSS Feed

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:        # allow manual runs from the Actions tab

permissions:
  contents: write           # allow this workflow to push the XML file back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate feed
        run: python abat_sec_feed.py

      - name: Commit and push feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add abat_sec_filings.xml || true
          git commit -m "Update SEC RSS feed" || echo "No changes to commit"
          git push
